# font face Iosevka (bold)

command_timeout = 500
format = "$all"

[character]
success_symbol = "[❯❯](black #FFA500) "
error_symbol = "[❯❯](black red) "

[cmd_duration]
min_time = 500
format = "took [$duration](bold yellow) "

#[directory]
#read_only = " "
#truncation_length = 3
#truncation_symbol = "~/"

[directory]
truncation_length = 100
truncate_to_repo = false
style = "#FFA500"
format = "[$path]($style)[$read_only]($read_only_style) "

[git_branch]
symbol = "  "
style = "bold #fdfd96 inverted"
format = "on [$symbol$branch ]($style) "

[python]
format = "[$symbol$version]($style) "
style = "bold #90EE90"

[nodejs]
format = "[$symbol$version]($style) "
style = "bold yellow"

[git_commit]
commit_hash_length = 8
style = "white"

[git_status]
# I don't care about untracked files or that there's a stash present.
untracked = ""
deleted = "X"
style = "#FFA500"
format = '([\[$conflicted$deleted$renamed$modified$staged$behind\]]($style) )'
modified = 'M'

[package]
disabled = false